module.exports = {
	'likes': '{ likes, number } me gusta',
	'logout': 'Salir',
	'english': 'Inglés',
	'spanich': 'Español',
	'signup.subheading': '¡Regístrate ahora!',
	'signup.facebook': 'Iniciar sesión con Facebook',
	'signup.text': 'Iniciar sesión',
	'email': 'Correo electrónico',
	'username': 'Usuario',
	'fullname': 'Nombre',
	'password': 'Contraseña',
	'signup.call-to-action': 'Regístrate',
	'signup.have-account': '¿Tienes una cuenta?',
	'signin': 'Entrar',
	'signin.not-have-account': '¿No tienes una cuenta?',
	'language': 'Idioma',
	'upload-picture': 'Subir imagen',
	'upload': 'Subir'
}